version: 3.0

services:
  mysql:
    image: mysql
    container-name: gpt-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myDB4322
      MYSQL_DATABASE: gpt-db
      MYSQL_USER: root
      MYSQL_PASSWORD: user123
    ports:
      - 3306:3306
    volume:
      - docker/mysql:/var/lib/mysql