// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Chat struct {
	ID               string
	UserID           string
	InitialMessageID string
	Status           string
	TokenUsage       int16
	Model            string
	ModelMaxTokens   int16
	Temperature      float64
	TopP             float64
	N                int16
	Stop             string
	MaxTokens        int16
	PresencePenalty  float64
	FrequencyPenalty float64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Message struct {
	ID        string
	ChatID    string
	Role      string
	Content   string
	Tokens    int16
	Model     string
	Erased    bool
	OrderMsg  int16
	CreatedAt time.Time
}
